linters:
  enable:
    # Basic linters
    - errcheck      # Check for unchecked errors
    - goimports     # Manage imports and format code
    - revive        # Drop-in replacement for golint
    - govet         # Reports suspicious constructs
    - staticcheck   # Advanced static analysis
    - wrapcheck     # Checks that errors are wrapped with context
    - importas      # Enforce import aliases
    
    # Code quality linters
    - dogsled       # Checks for too many blank identifiers
    - gochecknoglobals  # Check for global variables
    - gosimple      # Simplify code
    - ineffassign   # Detect ineffective assignments
    - unconvert     # Remove unnecessary type conversions
    - unused        # Check for unused constants, variables, functions
    - misspell      # Check spelling
    
    # Performance linters
    - bodyclose     # Checks whether HTTP response bodies are closed
    - prealloc      # Find slice preallocation opportunities
    
    # Security linters
    - gosec        # Security checker

linters-settings:
  goimports:
    local-prefixes: github.com/jonesrussell/goforms
    forbidden-imports:
      - pattern: "go.uber.org/zap"
        except: ["github.com/jonesrussell/goforms/internal/logger"]

  importas:
    no-unaliased: true
    alias:
      - pkg: go.uber.org/zap
        alias: forbidden_zap

  gochecknoglobals:
    ignore-fields: true
    ignore-patterns:
      - .*Module.*  # Ignore all fx module variables
      - .*Logger.*  # Ignore logger-related variables
    ignore-names:
      - instance    # Ignore singleton instances
      - once       # Ignore sync.Once instances
      - logger     # Ignore logger instances

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .Struct(
      - .ExecContext(
      - .SelectContext(
      - .SignedString(
      - .Parse(
      - .GenerateFromPassword(
      - .GetByEmail(
      - .Create(
      - .Update(
      - .Delete(
      - .List(
    ignorePackageGlobs:
      - github.com/jonesrussell/goforms/internal/logger
      - github.com/jonesrussell/goforms/internal/response
      - github.com/jonesrussell/goforms/internal/domain/*
      - github.com/jonesrussell/goforms/internal/application/*
      - github.com/labstack/echo/v4
      - github.com/stretchr/testify/*
      - github.com/a-h/templ
      - encoding/json
      - database/sql
      - github.com/jmoiron/sqlx
      - github.com/go-playground/validator/v10
      - github.com/golang-jwt/jwt/v5
      - golang.org/x/crypto/bcrypt

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
  
  gosec:
    excludes:
      - G104  # Audit errors not checked
      
  govet:
    checks:
      - shadow
      - fieldalignment

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gochecknoglobals
        - gosec
        - wrapcheck
    - path: internal/infrastructure/logging/logger.go
      linters:
        - gochecknoglobals
        - importas
    - path: internal/models/mocks.go
      linters:
        - wrapcheck
    - path: test/
      linters:
        - wrapcheck
    - path: internal/models/
      linters:
        - wrapcheck
  
  max-issues-per-linter: 50
  max-same-issues: 10
  fix: true
