version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
      - go mod download
      - go mod tidy
      - go install github.com/a-h/templ/cmd/templ@latest

  generate:
    desc: Generate templ files
    cmds:
      - templ generate ./internal/...

  dev:
    desc: Run development server
    deps: [install, generate]
    cmds:
      - go run ./cmd/goforms

  build:
    desc: Build for production
    deps: [install, generate]
    cmds:
      - go build -o bin/goforms ./cmd/goforms

  test:
    desc: Run tests
    deps: [generate]
    cmds:
      - go test -v ./...

  lint:
    desc: Run linters
    deps: [generate]
    cmds:
      - golangci-lint run

  migrate:
    desc: Run database migrations
    cmds:
      - go run cmd/migrate/main.go
