# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
output: 'prefixed'

includes:
  migrate:
    taskfile: Taskfile.migrate.yml
    namespace: migrate
  user:
    taskfile: Taskfile.user.yml
    namespace: user

dotenv: ['.env']

vars:
  VERSION:
    sh: git describe --tags --always --dirty
  BUILD_TIME:
    sh: date -u '+%Y-%m-%d_%H:%M:%S'
  GIT_COMMIT:
    sh: git rev-parse HEAD
  GO_VERSION:
    sh: go version | cut -d ' ' -f 3
  LDFLAGS: -s -w -X main.version={{.VERSION}} -X main.buildTime={{.BUILD_TIME}} -X main.gitCommit={{.GIT_COMMIT}} -X main.goVersion={{.GO_VERSION}}
  DB_USER: '{{.DB_USER}}'
  DB_PASSWORD: '{{.DB_PASSWORD}}'
  DB_NAME: '{{.DB_NAME}}'
  DB_HOST: '{{.DB_HOST}}'
  DB_PORT: '{{.DB_PORT}}'
  DB_ROOT_PASSWORD: '{{.DB_ROOT_PASSWORD}}'
  TEST_DB_USER: '{{.TEST_DB_USER}}'
  TEST_DB_PASSWORD: '{{.TEST_DB_PASSWORD}}'
  TEST_DB_NAME: '{{.TEST_DB_NAME}}'
  TEST_DB_HOST: '{{.TEST_DB_HOST}}'
  TEST_DB_PORT: '{{.TEST_DB_PORT}}'
  PROD_USER: '{{.PROD_USER}}'
  PROD_SERVER: '{{.PROD_SERVER}}'
  PROD_LOG_PATH: '{{.PROD_LOG_PATH}}'

tasks:
  default:
    cmds:
      - task: install
      - task: generate
      - task: build
      - task: migrate:up
      - task: run

  verify:
    desc: Verify frontend code quality and types
    deps: [lint:frontend]
    cmds:
      - npm run typecheck
      - npm run format:check

  format:
    desc: Format frontend code
    cmds:
      - npm run format

  install:
    desc: Install project dependencies
    cmds:
      - go mod tidy
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/air-verse/air@latest
      - go install golang.org/x/lint/golint@latest
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
      - go install go.uber.org/mock/mockgen@latest
      - go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - export PATH=$PATH:$(go env GOPATH)/bin
      - npm install

  generate:
    desc: Generate code from templates
    cmds:
      - templ generate ./internal/...
      - mockgen -source=internal/infrastructure/logging/types.go -destination=test/mocks/logging/mock_logger.go -package=logging

  build:
    desc: Build the application (frontend and backend in parallel)
    deps: [generate, format, verify]
    cmds:
      - task: build:frontend
      - task: build:backend

  build:frontend:
    desc: Build the frontend application
    cmds:
      - npm run build

  build:backend:
    desc: Build the backend application
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o bin/server ./cmd/goforms

  run:
    desc: Run the application
    cmds:
      - ./bin/server

  dev:
    desc: Run development environment
    deps: [dev:backend, dev:frontend]

  dev:backend:
    desc: Run backend with hot reload
    deps: [generate]
    cmds:
      - air

  dev:frontend:
    desc: Run frontend development server
    cmds:
      - npx vite --host 0.0.0.0 --port 3000

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/ dist/ node_modules/ coverage/
      - find internal/ -name '*_templ.go' -delete

  lint:
    desc: Run linters for all code
    deps: [lint:backend, lint:frontend]

  lint:backend:
    desc: Run linters for Go
    cmds:
      - go fmt ./...
      - go vet ./...
      # - golint ./...
      - golangci-lint run ./...

  lint:frontend:
    desc: Run linters for frontend code
    cmds:
      - npm run lint

  lint:fix:
    desc: Fix linting issues in all code
    deps: [lint:fix:backend, lint:fix:frontend]

  lint:fix:backend:
    desc: Fix linting issues in Go code
    cmds:
      - go fmt ./...

  lint:fix:frontend:
    desc: Fix linting issues in frontend code
    cmds:
      - npm run lint:fix

  test:
    desc: Run all tests
    deps: [generate]
    cmds:
      - go test -v -race -coverprofile=coverage.out -covermode=atomic ./internal/...
      - go tool cover -html=coverage.out -o coverage.html

  logs:
    desc: View production logs
    cmds:
      - ssh {{.PROD_USER}}@{{.PROD_SERVER}} "tail -f -n 100 {{.PROD_LOG_PATH}}/goforms.{out,err}.log"
