version: '3'

vars:
  VERSION:
    sh: git describe --tags --always --dirty
  BUILD_TIME:
    sh: date -u '+%Y-%m-%d_%H:%M:%S'
  GIT_COMMIT:
    sh: git rev-parse HEAD
  GO_VERSION:
    sh: go version | cut -d ' ' -f 3
  DB_URL:
    sh: echo "mysql://${DB_USER}:${DB_PASSWORD}@tcp(${DB_HOSTNAME}:${DB_PORT})/${DB_NAME}"

tasks:
  install:
    desc: Install dependencies
    cmds:
      - go mod download
      - go mod tidy
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

  generate:
    desc: Generate templ files
    cmds:
      - templ generate ./internal/...

  dev:
    desc: Run development server
    deps: [install, generate]
    cmds:
      - go run ./cmd/goforms

  build:
    desc: Build for production
    deps: [install, generate, lint, test]
    cmds:
      - mkdir -p bin
      - |
        LDFLAGS="-s -w \
          -X main.version=$(git describe --tags --always --dirty) \
          -X main.buildTime=$(date -u '+%Y-%m-%d_%H:%M:%S') \
          -X main.gitCommit=$(git rev-parse HEAD) \
          -X main.goVersion=$(go version | cut -d ' ' -f 3)"
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -trimpath -ldflags "$LDFLAGS" -o bin/goforms-linux-amd64 ./cmd/goforms
        GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -trimpath -ldflags "$LDFLAGS" -o bin/goforms-darwin-amd64 ./cmd/goforms
        GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -trimpath -ldflags "$LDFLAGS" -o bin/goforms-windows-amd64.exe ./cmd/goforms
      - echo "Build completed successfully!"
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/goforms-linux-amd64
      - bin/goforms-darwin-amd64
      - bin/goforms-windows-amd64.exe
    method: checksum

  test:
    desc: Run tests
    deps: [generate]
    cmds:
      - go test -v -race -cover ./...

  lint:
    desc: Run linters
    deps: [generate]
    cmds:
      - golangci-lint run

  migrate:up:
    desc: Run database migrations up
    cmds:
      - migrate -database "{{.DB_URL}}" -path migrations up

  migrate:down:
    desc: Run database migrations down
    cmds:
      - migrate -database "{{.DB_URL}}" -path migrations down

  migrate:create:
    desc: Create a new migration
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.CLI_ARGS}}

  migrate:force:
    desc: Force set migration version
    cmds:
      - migrate -database "{{.DB_URL}}" -path migrations force {{.CLI_ARGS}}

  migrate:version:
    desc: Show current migration version
    cmds:
      - migrate -database "{{.DB_URL}}" -path migrations version

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - go clean -cache -testcache
