CREATE TABLE form_schemas (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    json_schema JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 