CREATE TABLE form_schemas (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    json_schema JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 