services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8090
      - GOFORMS_DB_CONNECTION=mariadb
      - GOFORMS_DB_HOST=db
      - GOFORMS_DB_PORT=3306
      - GOFORMS_DB_DATABASE=${DB_NAME}
      - GOFORMS_DB_USERNAME=${DB_USER}
      - GOFORMS_DB_PASSWORD=${DB_PASSWORD}
      - GOFORMS_DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - SECURITY_CORS_ALLOWED_ORIGINS=https://goforms.streetcode.net
    depends_on:
      db:
        condition: service_healthy
    networks:
      - goforms-net
    volumes:
      - ../../logs:/app/logs

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - goforms-net

networks:
  goforms-net:
    driver: bridge

volumes:
  mariadb-data: 