services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - go-cache:/go/pkg
    command: sleep infinity
    networks:
      - app-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
      - "8098:8080"  # For adminer
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - app-net

  adminer:
    image: adminer:latest
    restart: unless-stopped
    networks:
      - app-net
    depends_on:
      db:
        condition: service_healthy

volumes:
  mariadb-data:
  go-cache:
networks:
  app-net:

