services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - app-net
    ports:
      - "8090:8090"
      - "3000:3000"
    environment:
      - GOFORMS_DB_CONNECTION=postgres
      - GOFORMS_DB_HOST=postgres
      - GOFORMS_DB_PORT=5432
      - GOFORMS_DB_DATABASE=goforms
      - GOFORMS_DB_USERNAME=goforms
      - GOFORMS_DB_PASSWORD=goforms
      - GOFORMS_DB_SSLMODE=disable
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=goforms
      - POSTGRES_PASSWORD=goforms
      - POSTGRES_DB=goforms
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goforms"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - app-net

  adminer:
    image: adminer:latest
    restart: unless-stopped
    networks:
      - app-net
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8098:8080"

volumes:
  postgres-data:
networks:
  app-net:

