services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - app-net
    ports:
      - "8090:8090"
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MARIADB_ROOT_PASSWORD=toor
      - MARIADB_USER=goforms
      - MARIADB_PASSWORD=goforms
      - MARIADB_DATABASE=goforms
    ports:
      - "3306:3306"
      - "8098:8080"  # For adminer
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - app-net

  adminer:
    image: adminer:latest
    restart: unless-stopped
    networks:
      - app-net
    depends_on:
      db:
        condition: service_healthy

volumes:
  mariadb-data:
networks:
  app-net:

