name: Deploy to Production

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'production' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, openssl, zip

      - name: Install Deployer
        run: |
          curl -LO https://deployer.org/deployer.phar
          chmod +x deployer.phar
          sudo mv deployer.phar /usr/local/bin/dep

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to ${{ github.event.inputs.environment || 'production' }}
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          CSRF_SECRET: ${{ secrets.CSRF_SECRET }}
        run: |
          dep deploy ${{ github.event.inputs.environment || 'production' }} --hosts=${{ github.event.inputs.environment || 'production' }}

      - name: Notify deployment status
        if: always()
        run: |
          if [[ "${{ job.status }}" == "success" ]]; then
            echo "🎉 Deployment to ${{ github.event.inputs.environment || 'production' }} completed successfully!"
          else
            echo "❌ Deployment to ${{ github.event.inputs.environment || 'production' }} failed!"
          fi
