name: Go CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUNNING_IN_ACT: ${{ github.actor == 'nektos/act' }}

permissions:
  contents: read

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      go-cache: ${{ steps.go.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          lfs: true
          submodules: recursive

      - name: Set up Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
          cache-dependency-path: go.sum

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.2"
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Go tools
        uses: actions/cache@v4
        id: go-tools-cache
        with:
          path: |
            ~/go/bin
            ~/.cache/go-build
          key: ${{ runner.os }}-go-tools-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-tools-

      - name: Install dependencies
        if: steps.go-tools-cache.outputs.cache-hit != 'true'
        run: |
          echo "Running task --list"
          task --list
          echo "Running task install:all"
          task install:all

      - name: Install frontend dependencies
        run: task install:frontend

      - name: Build Frontend
        run: task build:frontend

      - name: Generate Mocks
        run: task generate:mocks:all

      - name: Generate Code
        run: task generate:all

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

  verify:
    name: Verify Code
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          lfs: true
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
          cache-dependency-path: go.sum

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.2"
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Go tools
        uses: actions/cache@v4
        id: go-tools-cache
        with:
          path: |
            ~/go/bin
            ~/.cache/go-build
          key: ${{ runner.os }}-go-tools-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-tools-

      - name: Install dependencies
        if: steps.go-tools-cache.outputs.cache-hit != 'true'
        run: task install:all

      - name: Install frontend dependencies
        run: task install:frontend

      - name: Build Frontend
        run: task build:frontend

      - name: Generate Mocks
        run: task generate:mocks:all

      - name: Generate Code
        run: task generate:all

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: task test

  build:
    name: Build Project
    needs: verify
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          lfs: true
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
          cache-dependency-path: go.sum

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.2"
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Go tools
        uses: actions/cache@v4
        id: go-tools-cache
        with:
          path: |
            ~/go/bin
            ~/.cache/go-build
          key: ${{ runner.os }}-go-tools-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-tools-

      - name: Install dependencies
        if: steps.go-tools-cache.outputs.cache-hit != 'true'
        run: task install:all

      - name: Install frontend dependencies
        run: task install:frontend

      - name: Build Frontend
        run: task build:frontend

      - name: Build
        run: |
          mkdir -p bin
          task generate:templ
          task build:all

      - name: List Artifacts
        run: ls -la bin/
