name: Go CI/CD

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

env:
  DB_USER: goforms_test
  DB_PASSWORD: goforms_test
  DB_NAME: goforms_test
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  TEST_DB_USER: goforms_test
  TEST_DB_PASSWORD: goforms_test
  TEST_DB_NAME: goforms_test
  TEST_DB_HOST: 127.0.0.1
  TEST_DB_PORT: 3306
  RUNNING_IN_ACT: ${{ github.actor == 'nektos/act' }}

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.11
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: goforms_test
          MYSQL_USER: goforms_test
          MYSQL_PASSWORD: goforms_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git describe

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
          cache-dependency-path: go.sum

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Generate files
        run: templ generate ./internal/...

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy

      - name: Run linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/migrate
          which migrate

      - name: Run migrations
        run: migrate -database "mysql://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@tcp(${{ env.DB_HOST }}:${{ env.DB_PORT }})/${{ env.DB_NAME }}" -path migrations up

      - name: Run tests
        run: task test

  build:
    name: Build
    needs: verify
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git describe

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
          cache-dependency-path: go.sum

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Generate files
        run: templ generate ./internal/...

      - name: Install dependencies
        run: |
          go mod download
          go mod tidy

      - name: Build all platforms
        run: |
          mkdir -p bin
          task build

      - name: List artifacts
        run: ls -la bin/

      # Skip artifact upload when running locally with act
      - name: Upload artifacts
        if: ${{ !env.RUNNING_IN_ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/
          retention-days: 7

      # Skip release creation when running locally with act
      - name: Create Release
        if: ${{ !env.RUNNING_IN_ACT && startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
          draft: false
          prerelease: false
          generate_release_notes: true
